package com.crawl.openapi.web.dto;

import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@NoArgsConstructor
public class CrawlingRequestDto {
    private String basin;
    private String oper;
    private String mngorg;
    private String obsknd;
    private String keynm;
    private String sort;
    private String bbsnnm;
    private String obscd;
    private String obsnm;
    private String clsyn;
    private String sbsncd;
    private String startdt;
    private String enddt;
    private String startyear;
    private String endyear;
    private String ym;
    private String dtrf;
    private String obsnmeng;
    private String opendt;
    private String addr;
    private String lon;
    private String lat;
    private String shgt;
    private String hrdtstart;
    private String hrdtend;
    private String dydtstart;
    private String dydtend;
    private String ymdh;
    private String rf;
    private String ymd;
    private String wlobscd;
    private String mggvcd;
    private String bbsncd;
    private String obsopndt;
    private String obskdcd;
    private String rivnm;
    private String bsnara;
    private String bedslp;
    private String rvwdt;
    private String rvmjctdis;
    private String wsrdis;
    private String tmx;
    private String tmy;
    private String gdt;
    private String wltel;
    private String tdeyn;
    private String mxgrd;
    private String sistartobsdh;
    private String siendobsdh;
    private String olstartobsdh;
    private String olendobsdh;
    private String wl;
    private String wtobscd;
    private String obselm;
    private String thrmlhi;
    private String prselm;
    private String wvmlhi;
    private String hytmlhi;
    private String nj;
    private String ta;
    private String hm;
    private String td;
    private String ps;
    private String ws;
    private String wd;
    private String sihr1;
    private String catot;
    private String sdtot;
    private String sshr1;
    private String taavg;
    private String tamin;
    private String tamax;
    private String wsavg;
    private String wsmax;
    private String wdmax;
    private String hmavg;
    private String hmmin;
    private String evs;
    private String evl;
    private String catotavg;
    private String psavg;
    private String psmax;
    private String psmin;
    private String sdmax;
    private String tdavg;
    private String siavg;
    private String ssavg;
    private String opndt;
    private String obsymd;
    private String obssthm;
    private String obsedhm;
    private String stwl;
    private String edwl;
    private String avgwl;
    private String rivwith;
    private String care;
    private String wspd;
    private String flw;
    private String obsway;
    private String docnm;
    private String minyear;
    private String maxyear;
    private String fw;
    private String year;
    private String obsymdhn;
    private String surcnt;
    private String capdsy;
    private String flqsv;
    private String wlcd;
    private String admcd;
    private String admnm;
    private String estcnt;
    private String ecpqty;
    private String fullara;
    private String pemara;
    private String sumara;
    private String nirara;
    private String pirara;
    private String oirara;
    private String mtcnt;
    private String mxvol;
    private String totirara;
    private String itqty;
    private String address;
    private String opymd;
    private String plmaxdrngblue;
    private String plmaxdrngrain;
    private String pumpname;
    private String plmax;
    private String wastwpcnt;
    private String rainwpcal;
    private String wastwpcal;
    private String wastwpdrng;
    private String rainwpdrng;
    private String rainwpcnt;
    private String elecppyn;
    private String deodoriyn;
    private String bsncd;
    private String bsnnm;
    private String drfq;
    private String edyr;
    private String estnm;
    private String esttype;
    private String mggvnm;
    private String mwsnm;
    private String wsdv;


    @Builder
    public CrawlingRequestDto(String bbsnnm, String obscd, String obsnm, String clsyn, String obsknd, String sbsncd, String mngorg, String ym, String dtrf, String obsnmeng, String opendt, String addr, String lon, String lat, String shgt, String hrdtstart, String hrdtend, String dydtstart, String dydtend, String ymdh, String rf, String ymd, String wlobscd, String mggvcd, String bbsncd, String obsopndt, String obskdcd, String rivnm, String bsnara, String rvwdt, String bedslp, String rvmjctdis, String wsrdis, String tmx, String tmy, String gdt, String wltel, String tdeyn, String mxgrd, String sistartobsdh, String siendobsdh, String olstartobsdh, String olendobsdh, String wl, String wtobscd, String obselm, String thrmlhi, String prselm, String wvmlhi, String hytmlhi, String nj, String ta, String hm, String td, String ps, String ws, String wd, String sihr1, String catot, String sdtot, String sshr1, String taavg, String tamin, String tamax, String wsavg, String wsmax, String wdmax, String hmavg, String hmmin, String evs, String evl, String catotavg, String psavg, String psmax, String psmin, String sdmax, String tdavg, String siavg, String ssavg, String opndt, String obsymd, String obssthm, String obsedhm, String stwl, String edwl, String avgwl, String rivwith, String care, String wspd, String flw, String obsway, String docnm, String minyear, String maxyear, String fw, String obsymdhn, String surcnt, String capdsy, String flqsv, String wlcd, String admnm, String admcd, String estcnt, String ecpqty, String fullara, String pemara, String sumara, String nirara, String pirara, String oirara, String mtcnt, String mxvol, String totirara, String itqty, String address, String opymd, String plmaxdrngblue, String plmaxdrngrain, String pumpname, String plmax, String wastwpcnt, String rainwpcal, String wastwpcal, String wastwpdrng, String rainwpdrng, String rainwpcnt, String elecppyn, String deodoriyn, String bsncd, String bsnnm, String drfq, String edyr, String estnm, String esttype, String mggvnm, String mwsnm, String wsdv){
        if(bbsnnm!="" && bbsnnm != null) this.bbsnnm = bbsnnm; else this.bbsnnm = "-";
        if(wsdv!="" && wsdv != null) this.wsdv = wsdv; else this.wsdv = "-";
        if(mwsnm!="" && mwsnm != null) this.mwsnm = mwsnm; else this.mwsnm = "-";
        if(mggvnm!="" && mggvnm != null) this.mggvnm = mggvnm; else this.mggvnm = "-";
        if(esttype!="" && esttype != null) this.esttype = esttype; else this.esttype = "-";
        if(estnm!="" && estnm != null) this.estnm = estnm; else this.estnm = "-";
        if(edyr!="" && edyr != null) this.edyr = edyr; else this.edyr = "-";
        if(drfq!="" && drfq != null) this.drfq = drfq; else this.drfq = "-";
        if(bsnnm!="" && bsnnm != null) this.bsnnm = bsnnm; else this.bsnnm = "-";
        if(bsncd!="" && bsncd != null) this.bsncd = bsncd; else this.bsncd = "-";
        if(deodoriyn!="" && deodoriyn != null) this.deodoriyn = deodoriyn; else this.deodoriyn = "-";
        if(elecppyn!="" && elecppyn != null) this.elecppyn = elecppyn; else this.elecppyn = "-";
        if(rainwpcnt!="" && rainwpcnt != null) this.rainwpcnt = rainwpcnt; else this.rainwpcnt = "-";
        if(rainwpdrng!="" && rainwpdrng != null) this.rainwpdrng = rainwpdrng; else this.rainwpdrng = "-";
        if(wastwpdrng!="" && wastwpdrng != null) this.wastwpdrng = wastwpdrng; else this.wastwpdrng = "-";
        if(wastwpcal!="" && wastwpcal != null) this.wastwpcal = wastwpcal; else this.wastwpcal = "-";
        if(rainwpcal!="" && rainwpcal != null) this.rainwpcal = rainwpcal; else this.rainwpcal = "-";
        if(wastwpcnt!="" && wastwpcnt != null) this.wastwpcnt = wastwpcnt; else this.wastwpcnt = "-";
        if(plmax!="" && plmax != null) this.plmax = plmax; else this.plmax = "-";
        if(plmaxdrngrain!="" && plmaxdrngrain != null) this.plmaxdrngrain = plmaxdrngrain; else this.plmaxdrngrain = "-";
        if(pumpname!="" && pumpname != null) this.pumpname = plmaxdrngrain; else this.pumpname = "-";
        if(plmaxdrngblue!="" && plmaxdrngblue != null) this.plmaxdrngblue = plmaxdrngblue; else this.plmaxdrngblue = "-";
        if(obscd!="" && obscd != null) this.obscd = obscd; else this.obscd = "-";
        if(obsnm!="" && obsnm != null) this.obsnm = obsnm; else this.obsnm = "-";
        if(clsyn!="" && clsyn != null) this.clsyn = clsyn; else this.clsyn = "-";
        if(obsknd!="" && obsknd != null) this.obsknd = obsknd; else this.obsknd = "-";
        if(sbsncd!="" && sbsncd != null) this.sbsncd = sbsncd; else this.sbsncd = "-";
        if(mngorg!="" && mngorg != null) this.mngorg = mngorg; else this.mngorg = "-";
        if(ym!="" && ym != null) this.ym = ym; else this.ym = "-";
        if(dtrf!="" && dtrf != null) this.dtrf = dtrf; else this.dtrf = "-";
        if(obsnmeng!="" && obsnmeng != null) this.obsnmeng = obsnmeng; else this.obsnmeng = "-";
        if(opendt!="" && opendt != null) this.opendt = opendt; else this.opendt = "-";
        if(addr!="" && addr != null) this.addr = addr; else this.addr = "-";
        if(lon!="" && lon != null) this.lon = lon; else this.lon = "-";
        if(lat!="" && lat != null) this.lat = lat; else this.lat = "-";
        if(shgt!="" && shgt != null) this.shgt = shgt; else this.shgt = "-";
        if(hrdtstart!="" && hrdtstart != null) this.hrdtstart = hrdtstart; else this.hrdtstart = "-";
        if(hrdtend!="" && hrdtend != null) this.hrdtend = hrdtend; else this.hrdtend = "-";
        if(dydtstart!="" && dydtstart != null) this.dydtstart = dydtstart; else this.dydtstart = "-";
        if(dydtend!="" && dydtend != null) this.dydtend = dydtend; else this.dydtend = "-";
        if(ymdh!="" && ymdh != null) this.ymdh = ymdh; else this.ymdh = "-";
        if(rf!="" && rf != null) this.rf = rf; else this.rf = "-";
        if(ymd!="" && ymd != null) this.ymd = ymd; else this.ymd = "-";
        if(wlobscd!="" && wlobscd != null) this.wlobscd = wlobscd; else this.wlobscd = "-";
        if(mggvcd!="" && mggvcd != null) this.mggvcd = mggvcd; else this.mggvcd = "-";
        if(bbsncd!="" && bbsncd != null) this.bbsncd = bbsncd; else this.bbsncd = "-";
        if(obsopndt!="" && obsopndt != null) this.obsopndt = obsopndt; else this.obsopndt = "-";
        if(obskdcd!="" && obskdcd != null) this.obskdcd = obskdcd; else this.obskdcd = "-";
        if(rivnm!="" && rivnm != null) this.rivnm = rivnm; else this.rivnm = "-";
        if(bsnara!="" && bsnara != null) this.bsnara = bsnara; else this.bsnara = "-";
        if(rvwdt!="" && rvwdt != null) this.rvwdt = rvwdt; else this.rvwdt = "-";
        if(bedslp!="" && bedslp != null) this.bedslp = bedslp; else this.bedslp = "-";
        if(rvmjctdis!="" && rvmjctdis != null) this.rvmjctdis = rvmjctdis; else this.rvmjctdis = "-";
        if(wsrdis!="" && wsrdis != null) this.wsrdis = wsrdis; else this.wsrdis = "-";
        if(tmx!="" && tmx != null) this.tmx = tmx; else this.tmx = "-";
        if(tmy!="" && tmy != null) this.tmy = tmy; else this.tmy = "-";
        if(gdt!="" && gdt != null) this.gdt = gdt; else this.gdt = "-";
        if(wltel!="" && wltel != null) this.wltel = wltel; else this.wltel = "-";
        if(tdeyn!="" && tdeyn != null) this.tdeyn = tdeyn; else this.tdeyn = "-";
        if(mxgrd!="" && mxgrd != null) this.mxgrd = mxgrd; else this.mxgrd = "-";
        if(sistartobsdh!="" && sistartobsdh != null) this.sistartobsdh = sistartobsdh; else this.sistartobsdh = "-";
        if(siendobsdh!="" && siendobsdh != null) this.siendobsdh = siendobsdh; else this.siendobsdh = "-";
        if(olstartobsdh!="" && olstartobsdh != null) this.olstartobsdh = olstartobsdh; else this.olstartobsdh = "-";
        if(olendobsdh!="" && olendobsdh != null) this.olendobsdh = olendobsdh; else this.olendobsdh = "-";
        if(wl!="" && wl != null) this.wl = wl; else this.wl = "-";
        if(wtobscd!="" && wtobscd != null) this.wtobscd = wtobscd; else this.wtobscd = "-";
        if(obselm!="" && obselm != null) this.obselm = obselm; else this.obselm = "-";
        if(thrmlhi!="" && thrmlhi != null) this.thrmlhi = thrmlhi; else this.thrmlhi = "-";
        if(prselm!="" && prselm != null) this.prselm = prselm; else this.prselm = "-";
        if(wvmlhi!="" && wvmlhi != null) this.wvmlhi = wvmlhi; else this.wvmlhi = "-";
        if(hytmlhi!="" && hytmlhi != null) this.hytmlhi = hytmlhi; else this.hytmlhi = "-";
        if(nj!="" && nj != null) this.nj = nj; else this.nj = "-";
        if(ta!="" && ta != null) this.ta = ta; else this.ta = "-";
        if(hm!="" && hm != null) this.hm = hm; else this.hm = "-";
        if(td!="" && td != null) this.td = td; else this.td = "-";
        if(ps!="" && ps != null) this.ps = ps; else this.ps = "-";
        if(ws!="" && ws != null) this.ws = ws; else this.ws = "-";
        if(wd!="" && wd != null) this.wd = wd; else this.wd = "-";
        if(sihr1!="" && sihr1 != null) this.sihr1 = sihr1; else this.sihr1 = "-";
        if(catot!="" && catot != null) this.catot = catot; else this.catot = "-";
        if(sdtot!="" && sdtot != null) this.sdtot = sdtot; else this.sdtot = "-";
        if(sshr1!="" && sshr1 != null) this.sshr1 = sshr1; else this.sshr1 = "-";
        if(taavg!="" && taavg != null) this.taavg = taavg; else this.taavg = "-";
        if(tamin!="" && tamin != null) this.tamin = tamin; else this.tamin = "-";
        if(tamax!="" && tamax != null) this.tamax = tamax; else this.tamax = "-";
        if(wsavg!="" && wsavg != null) this.wsavg = wsavg; else this.wsavg = "-";
        if(wsmax!="" && wsmax != null) this.wsmax = wsmax; else this.wsmax = "-";
        if(wdmax!="" && wdmax != null) this.wdmax = wdmax; else this.wdmax = "-";
        if(hmavg!="" && hmavg != null) this.hmavg = hmavg; else this.hmavg = "-";
        if(hmmin!="" && hmmin != null) this.hmmin = hmmin; else this.hmmin = "-";
        if(evs!="" && evs != null) this.evs = evs; else this.evs = "-";
        if(evl!="" && evl != null) this.evl = evl; else this.evl = "-";
        if(catotavg!="" && catotavg != null) this.catotavg = catotavg; else this.catotavg = "-";
        if(psavg!="" && psavg != null) this.psavg = psavg; else this.psavg = "-";
        if(psmax!="" && psmax != null) this.psmax = psmax; else this.psmax = "-";
        if(psmin!="" && psmin != null) this.psmin = psmin; else this.psmin = "-";
        if(sdmax!="" && sdmax != null) this.sdmax = sdmax; else this.sdmax = "-";
        if(tdavg!="" && tdavg != null) this.tdavg = tdavg; else this.tdavg = "-";
        if(siavg!="" && siavg != null) this.siavg = siavg; else this.siavg = "-";
        if(ssavg!="" && ssavg != null) this.ssavg = ssavg; else this.ssavg = "-";
        if(opndt!="" && opndt != null) this.opndt = opndt; else this.opndt = "-";
        if(obsymd!="" && obsymd != null) this.obsymd = obsymd; else this.obsymd = "-";
        if(obssthm!="" && obssthm != null) this.obssthm = obssthm; else this.obssthm = "-";
        if(obsedhm!="" && obsedhm != null) this.obsedhm = obsedhm; else this.obsedhm = "-";
        if(stwl!="" && stwl != null) this.stwl = stwl; else this.stwl = "-";
        if(edwl!="" && edwl != null) this.edwl = edwl; else this.edwl = "-";
        if(avgwl!="" && avgwl != null) this.avgwl = avgwl; else this.avgwl = "-";
        if(rivwith!="" && rivwith != null) this.rivwith = rivwith; else this.rivwith = "-";
        if(care!="" && care != null) this.care = care; else this.care = "-";
        if(wspd!="" && wspd != null) this.wspd = wspd; else this.wspd = "-";
        if(flw!="" && flw != null) this.flw = flw; else this.flw = "-";
        if(obsway!="" && obsway != null) this.obsway = obsway; else this.obsway = "-";
        if(docnm!="" && docnm != null) this.docnm = docnm; else this.docnm = "-";
        if(minyear!="" && minyear != null) this.minyear = minyear; else this.minyear = "-";
        if(maxyear!="" && maxyear != null) this.maxyear = maxyear; else this.maxyear = "-";
        if(fw!="" && fw != null) this.fw = fw; else this.fw = "-";
        if(obsymdhn!="" && obsymdhn != null) this.obsymdhn = obsymdhn; else this.obsymdhn = "-";
        if(surcnt!="" && surcnt != null) this.surcnt = surcnt; else this.surcnt = "-";
        if(capdsy!="" && capdsy != null) this.capdsy = capdsy; else this.capdsy = "-";
        if(flqsv!="" && flqsv != null) this.flqsv = flqsv; else this.flqsv = "-";
        if(wlcd!="" && wlcd != null) this.wlcd = wlcd; else this.wlcd = "-";
        if(admnm!="" && admnm != null) this.admnm = admnm; else this.admnm = "-";
        if(admcd!="" && admcd != null) this.admcd = admcd; else this.admcd = "-";
        if(estcnt!="" && estcnt != null) this.estcnt = estcnt; else this.estcnt = "-";
        if(ecpqty!="" && ecpqty != null) this.ecpqty = ecpqty; else this.ecpqty = "-";
        if(fullara!="" && fullara != null) this.fullara = fullara; else this.fullara = "-";
        if(pemara!="" && pemara != null) this.pemara = pemara; else this.pemara = "-";
        if(sumara!="" && sumara != null) this.sumara = sumara; else this.sumara = "-";
        if(nirara!="" && nirara != null) this.nirara = nirara; else this.nirara = "-";
        if(pirara!="" && pirara != null) this.pirara = pirara; else this.pirara = "-";
        if(oirara!="" && oirara != null) this.oirara = oirara; else this.oirara = "-";
        if(mtcnt!="" && mtcnt != null) this.mtcnt = mtcnt; else this.mtcnt = "-";
        if(mxvol!="" && mxvol != null) this.mxvol = mxvol; else this.mxvol = "-";
        if(totirara!="" && totirara != null) this.totirara = totirara; else this.totirara = "-";
        if(itqty!="" && itqty != null) this.itqty = itqty; else this.itqty = "-";
        if(address!="" && address != null) this.address = address; else this.address = "-";
        if(opymd!="" && opymd != null) this.opymd = opymd; else this.opymd = "-";
    }
}
