package com.crawl.openapi.web.dto;

import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@NoArgsConstructor
public class CrawlingRequestDto {
    private String basin;
    private String oper;
    private String mngorg;
    private String obsknd;
    private String keynm;
    private String sort;
    private String bbsnnm;
    private String obscd;
    private String obsnm;
    private String clsyn;
    private String sbsncd;
    private String startdt;
    private String enddt;
    private String startyear;
    private String endyear;
    private String ym;
    private String dtrf;
    private String obsnmeng;
    private String opendt;
    private String addr;
    private String lon;
    private String lat;
    private String shgt;
    private String hrdtstart;
    private String hrdtend;
    private String dydtstart;
    private String dydtend;
    private String ymdh;
    private String rf;
    private String ymd;
    private String wlobscd;
    private String mggvcd;
    private String bbsncd;
    private String obsopndt;
    private String obskdcd;
    private String rivnm;
    private String bsnara;
    private String bedslp;
    private String rvwdt;
    private String rvmjctdis;
    private String wsrdis;
    private String tmx;
    private String tmy;
    private String gdt;
    private String wltel;
    private String tdeyn;
    private String mxgrd;
    private String sistartobsdh;
    private String siendobsdh;
    private String olstartobsdh;
    private String olendobsdh;
    private String wl;
    private String wtobscd;
    private String obselm;
    private String thrmlhi;
    private String prselm;
    private String wvmlhi;
    private String hytmlhi;
    private String nj;
    private String ta;
    private String hm;
    private String td;
    private String ps;
    private String ws;
    private String wd;
    private String sihr1;
    private String catot;
    private String sdtot;
    private String sshr1;
    private String taavg;
    private String tamin;
    private String tamax;
    private String wsavg;
    private String wsmax;
    private String wdmax;
    private String hmavg;
    private String hmmin;
    private String evs;
    private String evl;
    private String catotavg;
    private String psavg;
    private String psmax;
    private String psmin;
    private String sdmax;
    private String tdavg;
    private String siavg;
    private String ssavg;
    private String opndt;
    private String obsymd;
    private String obssthm;
    private String obsedhm;
    private String stwl;
    private String edwl;
    private String avgwl;
    private String rivwith;
    private String care;
    private String wspd;
    private String flw;
    private String obsway;
    private String docnm;
    private String minyear;
    private String maxyear;
    private String fw;
    private String year;
    private String obsymdhn;
    private String surcnt;
    private String capdsy;
    private String flqsv;
    private String wlcd;
    private String admcd;
    private String admnm;
    private String estcnt;
    private String ecpqty;
    private String fullara;
    private String pemara;
    private String sumara;
    private String nirara;
    private String pirara;
    private String oirara;
    private String mtcnt;
    private String mxvol;
    private String totirara;
    private String itqty;
    private String address;
    private String opymd;
    private String plmaxdrngblue;
    private String plmaxdrngrain;
    private String pumpname;
    private String plmax;
    private String wastwpcnt;
    private String rainwpcal;
    private String wastwpcal;
    private String wastwpdrng;
    private String rainwpdrng;
    private String rainwpcnt;
    private String elecppyn;
    private String deodoriyn;
    private String bsncd;
    private String bsnnm;
    private String drfq;
    private String edyr;
    private String estnm;
    private String esttype;
    private String mggvnm;
    private String mwsnm;
    private String wsdv;
    private String bankcd;
    private String banklr;
    private String banknm;
    private String bankwith;
    private String ebmttp;
    private String edaddr;
    private String edch;
    private String inslp;
    private String len;
    private String outslp;
    private String plfwl;
    private String plfwv;
    private String plrivwith;
    private String rivdv;
    private String staddr;
    private String stch;
    private String code;
    private String stchm;
    private String stchs;
    private String edchm;
    private String edchs;
    private String sttmx;
    private String sttmy;
    private String edtmx;
    private String edtmy;
    private String outstn;
    private String instn;
    private String gatecnt;
    private String pgatecnt;
    private String pipecnt;
    private String pumtcnt;
    private String bodysf;
    private String etcsf;
    private String bkrdtp;
    private String mngrdtp;
    private String hgebmttp;
    private String hgebmtst;
    private String bedtp;
    private String bedst;
    private String lwebmttp;
    private String lwebmtst;
    private String waystn;
    private String crstp;
    private String bedsoil;
    private String mnggv;
    private String estcd;
    private String ndvol;
    private String ofara;
    private String pumpvol;
    private String rivlevl;
    private String rndl;
    private String strtp;
    private String mpnt;
    private String etcitm;
    private String pumplr;
    private String eststs;
    private String chain;
    private String lrdv;
    private String estlr;
    private String estdv;
    private String damcd;
    private String damnm;
    private String obsdh;
    private String rwl;
    private String ospilwl;
    private String rsqty;
    private String rsrt;
    private String iqty;
    private String etqty;
    private String tdqty;
    private String edqty;
    private String spdqty;
    private String otltdqty;
    private String dambsarf;
    private String mnwl;
    private String avwl;
    private String mxwl;
    private String mniqty;
    private String aviqty;
    private String mxiqty;
    private String mntdqty;
    private String avtdqty;
    private String mxtdqty;
    private String mnsqty;
    private String mxsqty;
    private String mnrf;
    private String avrf;
    private String mxrf;
    private String avsqty;
    private String total;
    private String wssum;
    private String indsum;
    private String afsum;
    private String wstot;
    private String wsuse;
    private String eluse;
    private String etuse;
    private String tsum;
    private String pwsu;
    private String fwsu;
    private String totflnd;
    private String totpdy;
    private String totls;


    @Builder
    public CrawlingRequestDto(String bbsnnm, String obscd, String obsnm, String clsyn, String obsknd, String sbsncd, String mngorg, String ym, String dtrf, String obsnmeng, String opendt, String addr, String lon, String lat, String shgt, String hrdtstart, String hrdtend, String dydtstart, String dydtend, String ymdh, String rf, String ymd, String wlobscd, String mggvcd, String bbsncd, String obsopndt, String obskdcd, String rivnm, String bsnara, String rvwdt, String bedslp, String rvmjctdis, String wsrdis, String tmx, String tmy, String gdt, String wltel, String tdeyn, String mxgrd, String sistartobsdh, String siendobsdh, String olstartobsdh, String olendobsdh, String wl, String wtobscd, String obselm, String thrmlhi, String prselm, String wvmlhi, String hytmlhi, String nj, String ta, String hm, String td, String ps, String ws, String wd, String sihr1, String catot, String sdtot, String sshr1, String taavg, String tamin, String tamax, String wsavg, String wsmax, String wdmax, String hmavg, String hmmin, String evs, String evl, String catotavg, String psavg, String psmax, String psmin, String sdmax, String tdavg, String siavg, String ssavg, String opndt, String obsymd, String obssthm, String obsedhm, String stwl, String edwl, String avgwl, String rivwith, String care, String wspd, String flw, String obsway, String docnm, String minyear, String maxyear, String fw, String obsymdhn, String surcnt, String capdsy, String flqsv, String wlcd, String admnm, String admcd, String estcnt, String ecpqty, String fullara, String pemara, String sumara, String nirara, String pirara, String oirara, String mtcnt, String mxvol, String totirara, String itqty, String address, String opymd, String plmaxdrngblue, String plmaxdrngrain, String pumpname, String plmax, String wastwpcnt, String rainwpcal, String wastwpcal, String wastwpdrng, String rainwpdrng, String rainwpcnt, String elecppyn, String deodoriyn, String bsncd, String bsnnm, String drfq, String edyr, String estnm, String esttype, String mggvnm, String mwsnm, String wsdv, String bankcd, String banklr, String banknm, String bankwith, String ebmttp, String edaddr, String edch, String inslp, String len, String outslp, String plfwl, String plfwv, String plrivwith, String rivdv, String staddr, String stch, String stchm, String stchs, String edchm, String edchs, String sttmx, String sttmy, String edtmx, String edtmy, String outstn, String instn, String gatecnt, String pgatecnt, String pipecnt, String pumtcnt, String bodysf, String etcsf, String mngrdtp, String bkrdtp, String hgebmttp, String hgebmtst, String bedtp, String bedst, String lwebmttp, String lwebmtst, String waystn, String crstp, String bedsoil, String mnggv, String estcd, String ndvol, String ofara, String pumpvol, String rivlevl, String rndl, String strtp, String mpnt, String etcitm, String pumplr, String eststs, String chain, String lrdv, String estlr, String estdv, String damcd, String damnm, String obsdh, String rwl, String ospilwl, String rsqty, String rsrt, String iqty, String etqty, String tdqty, String edqty, String spdqty, String otltdqty, String dambsarf, String mnwl, String avwl, String mxwl, String mniqty, String aviqty, String mxiqty, String mntdqty, String avtdqty, String mxtdqty, String mnsqty, String mxsqty, String mnrf, String avrf, String mxrf, String avsqty, String year, String total, String wssum, String indsum, String afsum, String wstot, String wsuse, String eluse, String etuse, String tsum, String pwsu, String fwsu, String totflnd, String totpdy, String totls){
        if(bbsnnm!="" && bbsnnm != null) this.bbsnnm = bbsnnm; else this.bbsnnm = "-";
        if(totls!="" && totls != null) this.totls = totls; else this.totls = "-";
        if(totpdy!="" && totpdy != null) this.totpdy = totpdy; else this.totpdy = "-";
        if(totflnd!="" && totflnd != null) this.totflnd = totflnd; else this.totflnd = "-";
        if(fwsu!="" && fwsu != null) this.fwsu = fwsu; else this.fwsu = "-";
        if(pwsu!="" && pwsu != null) this.pwsu = pwsu; else this.pwsu = "-";
        if(tsum!="" && tsum != null) this.tsum = tsum; else this.tsum = "-";
        if(etuse!="" && etuse != null) this.etuse = etuse; else this.etuse = "-";
        if(eluse!="" && eluse != null) this.eluse = eluse; else this.eluse = "-";
        if(wsuse!="" && wsuse != null) this.wsuse = wsuse; else this.wsuse = "-";
        if(wstot!="" && wstot != null) this.wstot = wstot; else this.wstot = "-";
        if(afsum!="" && afsum != null) this.afsum = afsum; else this.afsum = "-";
        if(indsum!="" && indsum != null) this.indsum = indsum; else this.indsum = "-";
        if(wssum!="" && wssum != null) this.wssum = wssum; else this.wssum = "-";
        if(total!="" && total != null) this.total = total; else this.total = "-";
        if(year!="" && year != null) this.year = year; else this.year = "-";
        if(avsqty!="" && avsqty != null) this.avsqty = avsqty; else this.avsqty = "-";
        if(mxrf!="" && mxrf != null) this.mxrf = mxrf; else this.mxrf = "-";
        if(avrf!="" && avrf != null) this.avrf = avrf; else this.avrf = "-";
        if(mnrf!="" && mnrf != null) this.mnrf = mnrf; else this.mnrf = "-";
        if(mxsqty!="" && mxsqty != null) this.mxsqty = mxsqty; else this.mxsqty = "-";
        if(mnsqty!="" && mnsqty != null) this.mnsqty = mnsqty; else this.mnsqty = "-";
        if(mxtdqty!="" && mxtdqty != null) this.mxtdqty = mxtdqty; else this.mxtdqty = "-";
        if(avtdqty!="" && avtdqty != null) this.avtdqty = avtdqty; else this.avtdqty = "-";
        if(mntdqty!="" && mntdqty != null) this.mntdqty = mntdqty; else this.mntdqty = "-";
        if(mxiqty!="" && mxiqty != null) this.mxiqty = mxiqty; else this.mxiqty = "-";
        if(aviqty!="" && aviqty != null) this.aviqty = aviqty; else this.aviqty = "-";
        if(mniqty!="" && mniqty != null) this.mniqty = mniqty; else this.mniqty = "-";
        if(mxwl!="" && mxwl != null) this.mxwl = mxwl; else this.mxwl = "-";
        if(avwl!="" && avwl != null) this.avwl = avwl; else this.avwl = "-";
        if(mnwl!="" && mnwl != null) this.mnwl = mnwl; else this.mnwl = "-";
        if(dambsarf!="" && dambsarf != null) this.dambsarf = dambsarf; else this.dambsarf = "-";
        if(otltdqty!="" && otltdqty != null) this.otltdqty = otltdqty; else this.otltdqty = "-";
        if(spdqty!="" && spdqty != null) this.spdqty = spdqty; else this.spdqty = "-";
        if(edqty!="" && edqty != null) this.edqty = edqty; else this.edqty = "-";
        if(tdqty!="" && tdqty != null) this.tdqty = tdqty; else this.tdqty = "-";
        if(etqty!="" && etqty != null) this.etqty = etqty; else this.etqty = "-";
        if(iqty!="" && iqty != null) this.iqty = iqty; else this.iqty = "-";
        if(rsrt!="" && rsrt != null) this.rsrt = rsrt; else this.rsrt = "-";
        if(rsqty!="" && rsqty != null) this.rsqty = rsqty; else this.rsqty = "-";
        if(ospilwl!="" && ospilwl != null) this.ospilwl = ospilwl; else this.ospilwl = "-";
        if(rwl!="" && rwl != null) this.rwl = rwl; else this.rwl = "-";
        if(obsdh!="" && obsdh != null) this.obsdh = obsdh; else this.obsdh = "-";
        if(damnm!="" && damnm != null) this.damnm = damnm; else this.damnm = "-";
        if(damcd!="" && damcd != null) this.damcd = damcd; else this.damcd = "-";
        if(estdv!="" && estdv != null) this.estdv = estdv; else this.estdv = "-";
        if(estlr!="" && estlr != null) this.estlr = estlr; else this.estlr = "-";
        if(lrdv!="" && lrdv != null) this.lrdv = lrdv; else this.lrdv = "-";
        if(chain!="" && chain != null) this.chain = chain; else this.chain = "-";
        if(eststs!="" && eststs != null) this.eststs = eststs; else this.eststs = "-";
        if(pumplr!="" && pumplr != null) this.pumplr = pumplr; else this.pumplr = "-";
        if(etcitm!="" && etcitm != null) this.etcitm = etcitm; else this.etcitm = "-";
        if(mpnt!="" && mpnt != null) this.mpnt = mpnt; else this.mpnt = "-";
        if(strtp!="" && strtp != null) this.strtp = strtp; else this.strtp = "-";
        if(rndl!="" && rndl != null) this.rndl = rndl; else this.rndl = "-";
        if(rivlevl!="" && rivlevl != null) this.rivlevl = rivlevl; else this.rivlevl = "-";
        if(pumpvol!="" && pumpvol != null) this.pumpvol = pumpvol; else this.pumpvol = "-";
        if(ofara!="" && ofara != null) this.ofara = ofara; else this.ofara = "-";
        if(ndvol!="" && ndvol != null) this.ndvol = ndvol; else this.ndvol = "-";
        if(estcd!="" && estcd != null) this.estcd = estcd; else this.estcd = "-";
        if(mnggv!="" && mnggv != null) this.mnggv = mnggv; else this.mnggv = "-";
        if(bedsoil!="" && bedsoil != null) this.bedsoil = bedsoil; else this.bedsoil = "-";
        if(crstp!="" && crstp != null) this.crstp = crstp; else this.crstp = "-";
        if(waystn!="" && waystn != null) this.waystn = waystn; else this.waystn = "-";
        if(lwebmtst!="" && lwebmtst != null) this.lwebmtst = lwebmtst; else this.lwebmtst = "-";
        if(lwebmttp!="" && lwebmttp != null) this.lwebmttp = lwebmttp; else this.lwebmttp = "-";
        if(bedst!="" && bedst != null) this.bedst = bedst; else this.bedst = "-";
        if(bedtp!="" && bedtp != null) this.bedtp = bedtp; else this.bedtp = "-";
        if(hgebmtst!="" && hgebmtst != null) this.hgebmtst = hgebmtst; else this.hgebmtst = "-";
        if(hgebmttp!="" && hgebmttp != null) this.hgebmttp = hgebmttp; else this.hgebmttp = "-";
        if(bkrdtp!="" && bkrdtp != null) this.bkrdtp = bkrdtp; else this.bkrdtp = "-";
        if(mngrdtp!="" && mngrdtp != null) this.mngrdtp = mngrdtp; else this.mngrdtp = "-";
        if(etcsf!="" && etcsf != null) this.etcsf = etcsf; else this.etcsf = "-";
        if(bodysf!="" && bodysf != null) this.bodysf = bodysf; else this.bodysf = "-";
        if(pumtcnt!="" && pumtcnt != null) this.pumtcnt = pumtcnt; else this.pumtcnt = "-";
        if(pipecnt!="" && pipecnt != null) this.pipecnt = pipecnt; else this.pipecnt = "-";
        if(pgatecnt!="" && pgatecnt != null) this.pgatecnt = pgatecnt; else this.pgatecnt = "-";
        if(gatecnt!="" && gatecnt != null) this.gatecnt = gatecnt; else this.gatecnt = "-";
        if(instn!="" && instn != null) this.instn = instn; else this.instn = "-";
        if(outstn!="" && outstn != null) this.outstn = outstn; else this.outstn = "-";
        if(edtmy!="" && edtmy != null) this.edtmy = edtmy; else this.edtmy = "-";
        if(edtmx!="" && edtmx != null) this.edtmx = edtmx; else this.edtmx = "-";
        if(sttmy!="" && sttmy != null) this.sttmy = sttmy; else this.sttmy = "-";
        if(sttmx!="" && sttmx != null) this.sttmx = sttmx; else this.sttmx = "-";
        if(edchs!="" && edchs != null) this.edchs = edchs; else this.edchs = "-";
        if(edchm!="" && edchm != null) this.edchm = edchm; else this.edchm = "-";
        if(stchs!="" && stchs != null) this.stchs = stchs; else this.stchs = "-";
        if(stchm!="" && stchm != null) this.stchm = stchm; else this.stchm = "-";
        if(stch!="" && stch != null) this.stch = stch; else this.stch = "-";
        if(staddr!="" && staddr != null) this.staddr = staddr; else this.staddr = "-";
        if(rivdv!="" && rivdv != null) this.rivdv = rivdv; else this.rivdv = "-";
        if(plrivwith!="" && plrivwith != null) this.plrivwith = plrivwith; else this.plrivwith = "-";
        if(plfwv!="" && plfwv != null) this.plfwv = plfwv; else this.plfwv = "-";
        if(plfwl!="" && plfwl != null) this.plfwl = plfwl; else this.plfwl = "-";
        if(outslp!="" && outslp != null) this.outslp = outslp; else this.outslp = "-";
        if(len!="" && len != null) this.len = len; else this.len = "-";
        if(inslp!="" && inslp != null) this.inslp = inslp; else this.inslp = "-";
        if(edch!="" && edch != null) this.edch = edch; else this.edch = "-";
        if(edaddr!="" && edaddr != null) this.edaddr = edaddr; else this.edaddr = "-";
        if(ebmttp!="" && ebmttp != null) this.ebmttp = ebmttp; else this.ebmttp = "-";
        if(bankwith!="" && bankwith != null) this.bankwith = bankwith; else this.bankwith = "-";
        if(banknm!="" && banknm != null) this.banknm = banknm; else this.banknm = "-";
        if(banklr!="" && banklr != null) this.banklr = banklr; else this.banklr = "-";
        if(bankcd!="" && bankcd != null) this.bankcd = bankcd; else this.bankcd = "-";
        if(wsdv!="" && wsdv != null) this.wsdv = wsdv; else this.wsdv = "-";
        if(mwsnm!="" && mwsnm != null) this.mwsnm = mwsnm; else this.mwsnm = "-";
        if(mggvnm!="" && mggvnm != null) this.mggvnm = mggvnm; else this.mggvnm = "-";
        if(esttype!="" && esttype != null) this.esttype = esttype; else this.esttype = "-";
        if(estnm!="" && estnm != null) this.estnm = estnm; else this.estnm = "-";
        if(edyr!="" && edyr != null) this.edyr = edyr; else this.edyr = "-";
        if(drfq!="" && drfq != null) this.drfq = drfq; else this.drfq = "-";
        if(bsnnm!="" && bsnnm != null) this.bsnnm = bsnnm; else this.bsnnm = "-";
        if(bsncd!="" && bsncd != null) this.bsncd = bsncd; else this.bsncd = "-";
        if(deodoriyn!="" && deodoriyn != null) this.deodoriyn = deodoriyn; else this.deodoriyn = "-";
        if(elecppyn!="" && elecppyn != null) this.elecppyn = elecppyn; else this.elecppyn = "-";
        if(rainwpcnt!="" && rainwpcnt != null) this.rainwpcnt = rainwpcnt; else this.rainwpcnt = "-";
        if(rainwpdrng!="" && rainwpdrng != null) this.rainwpdrng = rainwpdrng; else this.rainwpdrng = "-";
        if(wastwpdrng!="" && wastwpdrng != null) this.wastwpdrng = wastwpdrng; else this.wastwpdrng = "-";
        if(wastwpcal!="" && wastwpcal != null) this.wastwpcal = wastwpcal; else this.wastwpcal = "-";
        if(rainwpcal!="" && rainwpcal != null) this.rainwpcal = rainwpcal; else this.rainwpcal = "-";
        if(wastwpcnt!="" && wastwpcnt != null) this.wastwpcnt = wastwpcnt; else this.wastwpcnt = "-";
        if(plmax!="" && plmax != null) this.plmax = plmax; else this.plmax = "-";
        if(plmaxdrngrain!="" && plmaxdrngrain != null) this.plmaxdrngrain = plmaxdrngrain; else this.plmaxdrngrain = "-";
        if(pumpname!="" && pumpname != null) this.pumpname = plmaxdrngrain; else this.pumpname = "-";
        if(plmaxdrngblue!="" && plmaxdrngblue != null) this.plmaxdrngblue = plmaxdrngblue; else this.plmaxdrngblue = "-";
        if(obscd!="" && obscd != null) this.obscd = obscd; else this.obscd = "-";
        if(obsnm!="" && obsnm != null) this.obsnm = obsnm; else this.obsnm = "-";
        if(clsyn!="" && clsyn != null) this.clsyn = clsyn; else this.clsyn = "-";
        if(obsknd!="" && obsknd != null) this.obsknd = obsknd; else this.obsknd = "-";
        if(sbsncd!="" && sbsncd != null) this.sbsncd = sbsncd; else this.sbsncd = "-";
        if(mngorg!="" && mngorg != null) this.mngorg = mngorg; else this.mngorg = "-";
        if(ym!="" && ym != null) this.ym = ym; else this.ym = "-";
        if(dtrf!="" && dtrf != null) this.dtrf = dtrf; else this.dtrf = "-";
        if(obsnmeng!="" && obsnmeng != null) this.obsnmeng = obsnmeng; else this.obsnmeng = "-";
        if(opendt!="" && opendt != null) this.opendt = opendt; else this.opendt = "-";
        if(addr!="" && addr != null) this.addr = addr; else this.addr = "-";
        if(lon!="" && lon != null) this.lon = lon; else this.lon = "-";
        if(lat!="" && lat != null) this.lat = lat; else this.lat = "-";
        if(shgt!="" && shgt != null) this.shgt = shgt; else this.shgt = "-";
        if(hrdtstart!="" && hrdtstart != null) this.hrdtstart = hrdtstart; else this.hrdtstart = "-";
        if(hrdtend!="" && hrdtend != null) this.hrdtend = hrdtend; else this.hrdtend = "-";
        if(dydtstart!="" && dydtstart != null) this.dydtstart = dydtstart; else this.dydtstart = "-";
        if(dydtend!="" && dydtend != null) this.dydtend = dydtend; else this.dydtend = "-";
        if(ymdh!="" && ymdh != null) this.ymdh = ymdh; else this.ymdh = "-";
        if(rf!="" && rf != null) this.rf = rf; else this.rf = "-";
        if(ymd!="" && ymd != null) this.ymd = ymd; else this.ymd = "-";
        if(wlobscd!="" && wlobscd != null) this.wlobscd = wlobscd; else this.wlobscd = "-";
        if(mggvcd!="" && mggvcd != null) this.mggvcd = mggvcd; else this.mggvcd = "-";
        if(bbsncd!="" && bbsncd != null) this.bbsncd = bbsncd; else this.bbsncd = "-";
        if(obsopndt!="" && obsopndt != null) this.obsopndt = obsopndt; else this.obsopndt = "-";
        if(obskdcd!="" && obskdcd != null) this.obskdcd = obskdcd; else this.obskdcd = "-";
        if(rivnm!="" && rivnm != null) this.rivnm = rivnm; else this.rivnm = "-";
        if(bsnara!="" && bsnara != null) this.bsnara = bsnara; else this.bsnara = "-";
        if(rvwdt!="" && rvwdt != null) this.rvwdt = rvwdt; else this.rvwdt = "-";
        if(bedslp!="" && bedslp != null) this.bedslp = bedslp; else this.bedslp = "-";
        if(rvmjctdis!="" && rvmjctdis != null) this.rvmjctdis = rvmjctdis; else this.rvmjctdis = "-";
        if(wsrdis!="" && wsrdis != null) this.wsrdis = wsrdis; else this.wsrdis = "-";
        if(tmx!="" && tmx != null) this.tmx = tmx; else this.tmx = "-";
        if(tmy!="" && tmy != null) this.tmy = tmy; else this.tmy = "-";
        if(gdt!="" && gdt != null) this.gdt = gdt; else this.gdt = "-";
        if(wltel!="" && wltel != null) this.wltel = wltel; else this.wltel = "-";
        if(tdeyn!="" && tdeyn != null) this.tdeyn = tdeyn; else this.tdeyn = "-";
        if(mxgrd!="" && mxgrd != null) this.mxgrd = mxgrd; else this.mxgrd = "-";
        if(sistartobsdh!="" && sistartobsdh != null) this.sistartobsdh = sistartobsdh; else this.sistartobsdh = "-";
        if(siendobsdh!="" && siendobsdh != null) this.siendobsdh = siendobsdh; else this.siendobsdh = "-";
        if(olstartobsdh!="" && olstartobsdh != null) this.olstartobsdh = olstartobsdh; else this.olstartobsdh = "-";
        if(olendobsdh!="" && olendobsdh != null) this.olendobsdh = olendobsdh; else this.olendobsdh = "-";
        if(wl!="" && wl != null) this.wl = wl; else this.wl = "-";
        if(wtobscd!="" && wtobscd != null) this.wtobscd = wtobscd; else this.wtobscd = "-";
        if(obselm!="" && obselm != null) this.obselm = obselm; else this.obselm = "-";
        if(thrmlhi!="" && thrmlhi != null) this.thrmlhi = thrmlhi; else this.thrmlhi = "-";
        if(prselm!="" && prselm != null) this.prselm = prselm; else this.prselm = "-";
        if(wvmlhi!="" && wvmlhi != null) this.wvmlhi = wvmlhi; else this.wvmlhi = "-";
        if(hytmlhi!="" && hytmlhi != null) this.hytmlhi = hytmlhi; else this.hytmlhi = "-";
        if(nj!="" && nj != null) this.nj = nj; else this.nj = "-";
        if(ta!="" && ta != null) this.ta = ta; else this.ta = "-";
        if(hm!="" && hm != null) this.hm = hm; else this.hm = "-";
        if(td!="" && td != null) this.td = td; else this.td = "-";
        if(ps!="" && ps != null) this.ps = ps; else this.ps = "-";
        if(ws!="" && ws != null) this.ws = ws; else this.ws = "-";
        if(wd!="" && wd != null) this.wd = wd; else this.wd = "-";
        if(sihr1!="" && sihr1 != null) this.sihr1 = sihr1; else this.sihr1 = "-";
        if(catot!="" && catot != null) this.catot = catot; else this.catot = "-";
        if(sdtot!="" && sdtot != null) this.sdtot = sdtot; else this.sdtot = "-";
        if(sshr1!="" && sshr1 != null) this.sshr1 = sshr1; else this.sshr1 = "-";
        if(taavg!="" && taavg != null) this.taavg = taavg; else this.taavg = "-";
        if(tamin!="" && tamin != null) this.tamin = tamin; else this.tamin = "-";
        if(tamax!="" && tamax != null) this.tamax = tamax; else this.tamax = "-";
        if(wsavg!="" && wsavg != null) this.wsavg = wsavg; else this.wsavg = "-";
        if(wsmax!="" && wsmax != null) this.wsmax = wsmax; else this.wsmax = "-";
        if(wdmax!="" && wdmax != null) this.wdmax = wdmax; else this.wdmax = "-";
        if(hmavg!="" && hmavg != null) this.hmavg = hmavg; else this.hmavg = "-";
        if(hmmin!="" && hmmin != null) this.hmmin = hmmin; else this.hmmin = "-";
        if(evs!="" && evs != null) this.evs = evs; else this.evs = "-";
        if(evl!="" && evl != null) this.evl = evl; else this.evl = "-";
        if(catotavg!="" && catotavg != null) this.catotavg = catotavg; else this.catotavg = "-";
        if(psavg!="" && psavg != null) this.psavg = psavg; else this.psavg = "-";
        if(psmax!="" && psmax != null) this.psmax = psmax; else this.psmax = "-";
        if(psmin!="" && psmin != null) this.psmin = psmin; else this.psmin = "-";
        if(sdmax!="" && sdmax != null) this.sdmax = sdmax; else this.sdmax = "-";
        if(tdavg!="" && tdavg != null) this.tdavg = tdavg; else this.tdavg = "-";
        if(siavg!="" && siavg != null) this.siavg = siavg; else this.siavg = "-";
        if(ssavg!="" && ssavg != null) this.ssavg = ssavg; else this.ssavg = "-";
        if(opndt!="" && opndt != null) this.opndt = opndt; else this.opndt = "-";
        if(obsymd!="" && obsymd != null) this.obsymd = obsymd; else this.obsymd = "-";
        if(obssthm!="" && obssthm != null) this.obssthm = obssthm; else this.obssthm = "-";
        if(obsedhm!="" && obsedhm != null) this.obsedhm = obsedhm; else this.obsedhm = "-";
        if(stwl!="" && stwl != null) this.stwl = stwl; else this.stwl = "-";
        if(edwl!="" && edwl != null) this.edwl = edwl; else this.edwl = "-";
        if(avgwl!="" && avgwl != null) this.avgwl = avgwl; else this.avgwl = "-";
        if(rivwith!="" && rivwith != null) this.rivwith = rivwith; else this.rivwith = "-";
        if(care!="" && care != null) this.care = care; else this.care = "-";
        if(wspd!="" && wspd != null) this.wspd = wspd; else this.wspd = "-";
        if(flw!="" && flw != null) this.flw = flw; else this.flw = "-";
        if(obsway!="" && obsway != null) this.obsway = obsway; else this.obsway = "-";
        if(docnm!="" && docnm != null) this.docnm = docnm; else this.docnm = "-";
        if(minyear!="" && minyear != null) this.minyear = minyear; else this.minyear = "-";
        if(maxyear!="" && maxyear != null) this.maxyear = maxyear; else this.maxyear = "-";
        if(fw!="" && fw != null) this.fw = fw; else this.fw = "-";
        if(obsymdhn!="" && obsymdhn != null) this.obsymdhn = obsymdhn; else this.obsymdhn = "-";
        if(surcnt!="" && surcnt != null) this.surcnt = surcnt; else this.surcnt = "-";
        if(capdsy!="" && capdsy != null) this.capdsy = capdsy; else this.capdsy = "-";
        if(flqsv!="" && flqsv != null) this.flqsv = flqsv; else this.flqsv = "-";
        if(wlcd!="" && wlcd != null) this.wlcd = wlcd; else this.wlcd = "-";
        if(admnm!="" && admnm != null) this.admnm = admnm; else this.admnm = "-";
        if(admcd!="" && admcd != null) this.admcd = admcd; else this.admcd = "-";
        if(estcnt!="" && estcnt != null) this.estcnt = estcnt; else this.estcnt = "-";
        if(ecpqty!="" && ecpqty != null) this.ecpqty = ecpqty; else this.ecpqty = "-";
        if(fullara!="" && fullara != null) this.fullara = fullara; else this.fullara = "-";
        if(pemara!="" && pemara != null) this.pemara = pemara; else this.pemara = "-";
        if(sumara!="" && sumara != null) this.sumara = sumara; else this.sumara = "-";
        if(nirara!="" && nirara != null) this.nirara = nirara; else this.nirara = "-";
        if(pirara!="" && pirara != null) this.pirara = pirara; else this.pirara = "-";
        if(oirara!="" && oirara != null) this.oirara = oirara; else this.oirara = "-";
        if(mtcnt!="" && mtcnt != null) this.mtcnt = mtcnt; else this.mtcnt = "-";
        if(mxvol!="" && mxvol != null) this.mxvol = mxvol; else this.mxvol = "-";
        if(totirara!="" && totirara != null) this.totirara = totirara; else this.totirara = "-";
        if(itqty!="" && itqty != null) this.itqty = itqty; else this.itqty = "-";
        if(address!="" && address != null) this.address = address; else this.address = "-";
        if(opymd!="" && opymd != null) this.opymd = opymd; else this.opymd = "-";
    }
}
