package com.crawl.openapi.web.dto;

import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@NoArgsConstructor
public class WeCrawlingRequestDto {
    private String basin;
    private String oper;
    private String keynm;
    private String sort;
    private String bbsnnm;
    private String obscd;
    private String obsnm;
    private String clsyn;
    private String obsknd;
    private String sbsncd;
    private String mngorg;
    private String addr;
    private String wtobscd;
    private String obskdcd;
    private String mggvcd;
    private String opndt;
    private String lon;
    private String lat;
    private String tmx;
    private String tmy;
    private String obselm;
    private String thrmlhi;
    private String prselm;
    private String wvmlhi;
    private String hytmlhi;
    private String nj;
    private String startdt;
    private String enddt;
    private String ymdh;
    private String ta;
    private String hm;
    private String td;
    private String ps;
    private String ws;
    private String wd;
    private String sihr1;
    private String catot;
    private String sdtot;
    private String sshr1;
    private String ymd;
    private String taavg;
    private String tamin;
    private String tamax;
    private String wsavg;
    private String wsmax;
    private String wdmax;
    private String hmavg;
    private String hmmin;
    private String evs;
    private String evl;
    private String catotavg;
    private String psavg;
    private String psmax;
    private String psmin;
    private String sdmax;
    private String tdavg;
    private String siavg;
    private String ssavg;
    private String bbsncd;

    @Builder
    public WeCrawlingRequestDto(String bbsnnm, String obscd, String obsnm, String clsyn, String obsknd, String sbsncd, String mngorg, String addr, String lon, String lat, String ymdh, String ymd, String mggvcd, String bbsncd, String obskdcd, String tmx, String tmy, String wtobscd, String obselm, String thrmlhi, String prselm, String wvmlhi, String hytmlhi, String nj, String ta, String hm, String td, String ps, String ws, String wd, String sihr1, String catot, String sdtot, String sshr1, String taavg, String tamin, String tamax, String wsavg, String wsmax, String wdmax, String hmavg, String hmmin, String evs, String evl, String catotavg, String psavg, String psmax, String psmin, String sdmax, String tdavg, String siavg, String ssavg, String opndt){
        if(bbsnnm!="" && bbsnnm != null) this.bbsnnm = bbsnnm; else this.bbsnnm = "-";
        if(obscd!="" && obscd != null) this.obscd = obscd; else this.obscd = "-";
        if(obsnm!="" && obsnm != null) this.obsnm = obsnm; else this.obsnm = "-";
        if(clsyn!="" && clsyn != null) this.clsyn = clsyn; else this.clsyn = "-";
        if(obsknd!="" && obsknd != null) this.obsknd = obsknd; else this.obsknd = "-";
        if(sbsncd!="" && sbsncd != null) this.sbsncd = sbsncd; else this.sbsncd = "-";
        if(mngorg!="" && mngorg != null) this.mngorg = mngorg; else this.mngorg = "-";
        if(addr!="" && addr != null) this.addr = addr; else this.addr = "-";
        if(lon!="" && lon != null) this.lon = lon; else this.lon = "-";
        if(lat!="" && lat != null) this.lat = lat; else this.lat = "-";
        if(ymdh!="" && ymdh != null) this.ymdh = ymdh; else this.ymdh = "-";
        if(ymd!="" && ymd != null) this.ymd = ymd; else this.ymd = "-";
        if(mggvcd!="" && mggvcd != null) this.mggvcd = mggvcd; else this.mggvcd = "-";
        if(bbsncd!="" && bbsncd != null) this.bbsncd = bbsncd; else this.bbsncd = "-";
        if(obskdcd!="" && obskdcd != null) this.obskdcd = obskdcd; else this.obskdcd = "-";
        if(tmx!="" && tmx != null) this.tmx = tmx; else this.tmx = "-";
        if(tmy!="" && tmy != null) this.tmy = tmy; else this.tmy = "-";
        if(wtobscd!="" && wtobscd != null) this.wtobscd = wtobscd; else this.wtobscd = "-";
        if(obselm!="" && obselm != null) this.obselm = obselm; else this.obselm = "-";
        if(thrmlhi!="" && thrmlhi != null) this.thrmlhi = thrmlhi; else this.thrmlhi = "-";
        if(prselm!="" && prselm != null) this.prselm = prselm; else this.prselm = "-";
        if(wvmlhi!="" && wvmlhi != null) this.wvmlhi = wvmlhi; else this.wvmlhi = "-";
        if(hytmlhi!="" && hytmlhi != null) this.hytmlhi = hytmlhi; else this.hytmlhi = "-";
        if(nj!="" && nj != null) this.nj = nj; else this.nj = "-";
        if(ta!="" && ta != null) this.ta = ta; else this.ta = "-";
        if(hm!="" && hm != null) this.hm = hm; else this.hm = "-";
        if(td!="" && td != null) this.td = td; else this.td = "-";
        if(ps!="" && ps != null) this.ps = ps; else this.ps = "-";
        if(ws!="" && ws != null) this.ws = ws; else this.ws = "-";
        if(wd!="" && wd != null) this.wd = wd; else this.wd = "-";
        if(sihr1!="" && sihr1 != null) this.sihr1 = sihr1; else this.sihr1 = "-";
        if(catot!="" && catot != null) this.catot = catot; else this.catot = "-";
        if(sdtot!="" && sdtot != null) this.sdtot = sdtot; else this.sdtot = "-";
        if(sshr1!="" && sshr1 != null) this.sshr1 = sshr1; else this.sshr1 = "-";
        if(taavg!="" && taavg != null) this.taavg = taavg; else this.taavg = "-";
        if(tamin!="" && tamin != null) this.tamin = tamin; else this.tamin = "-";
        if(tamax!="" && tamax != null) this.tamax = tamax; else this.tamax = "-";
        if(wsavg!="" && wsavg != null) this.wsavg = wsavg; else this.wsavg = "-";
        if(wsmax!="" && wsmax != null) this.wsmax = wsmax; else this.wsmax = "-";
        if(wdmax!="" && wdmax != null) this.wdmax = wdmax; else this.wdmax = "-";
        if(hmavg!="" && hmavg != null) this.hmavg = hmavg; else this.hmavg = "-";
        if(hmmin!="" && hmmin != null) this.hmmin = hmmin; else this.hmmin = "-";
        if(evs!="" && evs != null) this.evs = evs; else this.evs = "-";
        if(evl!="" && evl != null) this.evl = evl; else this.evl = "-";
        if(catotavg!="" && catotavg != null) this.catotavg = catotavg; else this.catotavg = "-";
        if(psavg!="" && psavg != null) this.psavg = psavg; else this.psavg = "-";
        if(psmax!="" && psmax != null) this.psmax = psmax; else this.psmax = "-";
        if(psmin!="" && psmin != null) this.psmin = psmin; else this.psmin = "-";
        if(sdmax!="" && sdmax != null) this.sdmax = sdmax; else this.sdmax = "-";
        if(tdavg!="" && tdavg != null) this.tdavg = tdavg; else this.tdavg = "-";
        if(siavg!="" && siavg != null) this.siavg = siavg; else this.siavg = "-";
        if(ssavg!="" && ssavg != null) this.ssavg = ssavg; else this.ssavg = "-";
        if(opndt!="" && opndt != null) this.opndt = opndt; else this.opndt = "-";
    }
}
