package com.crawl.openapi.web.dto;

import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@NoArgsConstructor
public class WkfCrawlingRequestDto {
    private String admcd;
    private String basin;
    private String bankcd;
    private String banklr;
    private String banknm;
    private String bankwith;
    private String ebmttp;
    private String edaddr;
    private String edch;
    private String inslp;
    private String len;
    private String outslp;
    private String plfwl;
    private String plfwv;
    private String plrivwith;
    private String rivdv;
    private String staddr;
    private String stch;
    private String code;
    private String rivnm;
    private String stchm;
    private String stchs;
    private String edchm;
    private String edchs;
    private String sttmx;
    private String sttmy;
    private String edtmx;
    private String edtmy;
    private String outstn;
    private String instn;
    private String gatecnt;
    private String pgatecnt;
    private String pipecnt;
    private String pumtcnt;
    private String bodysf;
    private String etcsf;
    private String bkrdtp;
    private String hgebmttp;
    private String hgebmtst;
    private String bedtp;
    private String bedst;
    private String lwebmttp;
    private String lwebmtst;
    private String waystn;
    private String crstp;
    private String bedsoil;
    private String mnggv;
    private String addr;
    private String estcd;
    private String estnm;
    private String ndvol;
    private String ofara;
    private String pumpvol;
    private String rivlevl;
    private String rndl;
    private String strtp;
    private String mpnt;
    private String etcitm;
    private String pumplr;
    private String lon;
    private String lat;
    private String tmx;
    private String tmy;
    private String eststs;
    private String bsncd;
    private String chain;
    private String lrdv;
    private String estlr;
    private String estdv;
    private String mngrdtp;

    @Builder
    public WkfCrawlingRequestDto(String mngrdtp, String addr, String lon, String lat, String rivnm, String tmx, String tmy, String admcd, String bsncd, String estnm, String bankcd, String banklr, String banknm, String bankwith, String ebmttp, String edaddr, String edch, String inslp, String len, String outslp, String plfwl, String plfwv, String plrivwith, String rivdv, String staddr, String stch, String stchm, String stchs, String edchm, String edchs, String sttmx, String sttmy, String edtmx, String edtmy, String outstn, String instn, String gatecnt, String pgatecnt, String pipecnt, String pumtcnt, String bodysf, String etcsf, String bkrdtp, String hgebmttp, String hgebmtst, String bedtp, String bedst, String lwebmttp, String lwebmtst, String waystn, String crstp, String bedsoil, String mnggv, String estcd, String ndvol, String ofara, String pumpvol, String rivlevl, String rndl, String strtp, String mpnt, String etcitm, String pumplr, String eststs, String chain, String lrdv, String estlr, String estdv){
        if(mngrdtp!="" && mngrdtp != null) this.mngrdtp = mngrdtp; else this.mngrdtp = "-";
        if(estdv!="" && estdv != null) this.estdv = estdv; else this.estdv = "-";
        if(estlr!="" && estlr != null) this.estlr = estlr; else this.estlr = "-";
        if(lrdv!="" && lrdv != null) this.lrdv = lrdv; else this.lrdv = "-";
        if(chain!="" && chain != null) this.chain = chain; else this.chain = "-";
        if(eststs!="" && eststs != null) this.eststs = eststs; else this.eststs = "-";
        if(pumplr!="" && pumplr != null) this.pumplr = pumplr; else this.pumplr = "-";
        if(etcitm!="" && etcitm != null) this.etcitm = etcitm; else this.etcitm = "-";
        if(mpnt!="" && mpnt != null) this.mpnt = mpnt; else this.mpnt = "-";
        if(strtp!="" && strtp != null) this.strtp = strtp; else this.strtp = "-";
        if(rndl!="" && rndl != null) this.rndl = rndl; else this.rndl = "-";
        if(rivlevl!="" && rivlevl != null) this.rivlevl = rivlevl; else this.rivlevl = "-";
        if(pumpvol!="" && pumpvol != null) this.pumpvol = pumpvol; else this.pumpvol = "-";
        if(ofara!="" && ofara != null) this.ofara = ofara; else this.ofara = "-";
        if(ndvol!="" && ndvol != null) this.ndvol = ndvol; else this.ndvol = "-";
        if(estcd!="" && estcd != null) this.estcd = estcd; else this.estcd = "-";
        if(mnggv!="" && mnggv != null) this.mnggv = mnggv; else this.mnggv = "-";
        if(bedsoil!="" && bedsoil != null) this.bedsoil = bedsoil; else this.bedsoil = "-";
        if(crstp!="" && crstp != null) this.crstp = crstp; else this.crstp = "-";
        if(waystn!="" && waystn != null) this.waystn = waystn; else this.waystn = "-";
        if(lwebmtst!="" && lwebmtst != null) this.lwebmtst = lwebmtst; else this.lwebmtst = "-";
        if(lwebmttp!="" && lwebmttp != null) this.lwebmttp = lwebmttp; else this.lwebmttp = "-";
        if(bedst!="" && bedst != null) this.bedst = bedst; else this.bedst = "-";
        if(bedtp!="" && bedtp != null) this.bedtp = bedtp; else this.bedtp = "-";
        if(hgebmtst!="" && hgebmtst != null) this.hgebmtst = hgebmtst; else this.hgebmtst = "-";
        if(hgebmttp!="" && hgebmttp != null) this.hgebmttp = hgebmttp; else this.hgebmttp = "-";
        if(bkrdtp!="" && bkrdtp != null) this.bkrdtp = bkrdtp; else this.bkrdtp = "-";
        if(etcsf!="" && etcsf != null) this.etcsf = etcsf; else this.etcsf = "-";
        if(bodysf!="" && bodysf != null) this.bodysf = bodysf; else this.bodysf = "-";
        if(pumtcnt!="" && pumtcnt != null) this.pumtcnt = pumtcnt; else this.pumtcnt = "-";
        if(pipecnt!="" && pipecnt != null) this.pipecnt = pipecnt; else this.pipecnt = "-";
        if(pgatecnt!="" && pgatecnt != null) this.pgatecnt = pgatecnt; else this.pgatecnt = "-";
        if(gatecnt!="" && gatecnt != null) this.gatecnt = gatecnt; else this.gatecnt = "-";
        if(instn!="" && instn != null) this.instn = instn; else this.instn = "-";
        if(outstn!="" && outstn != null) this.outstn = outstn; else this.outstn = "-";
        if(edtmy!="" && edtmy != null) this.edtmy = edtmy; else this.edtmy = "-";
        if(edtmx!="" && edtmx != null) this.edtmx = edtmx; else this.edtmx = "-";
        if(sttmy!="" && sttmy != null) this.sttmy = sttmy; else this.sttmy = "-";
        if(sttmx!="" && sttmx != null) this.sttmx = sttmx; else this.sttmx = "-";
        if(edchs!="" && edchs != null) this.edchs = edchs; else this.edchs = "-";
        if(edchm!="" && edchm != null) this.edchm = edchm; else this.edchm = "-";
        if(stchs!="" && stchs != null) this.stchs = stchs; else this.stchs = "-";
        if(stchm!="" && stchm != null) this.stchm = stchm; else this.stchm = "-";
        if(stch!="" && stch != null) this.stch = stch; else this.stch = "-";
        if(staddr!="" && staddr != null) this.staddr = staddr; else this.staddr = "-";
        if(rivdv!="" && rivdv != null) this.rivdv = rivdv; else this.rivdv = "-";
        if(plrivwith!="" && plrivwith != null) this.plrivwith = plrivwith; else this.plrivwith = "-";
        if(plfwv!="" && plfwv != null) this.plfwv = plfwv; else this.plfwv = "-";
        if(plfwl!="" && plfwl != null) this.plfwl = plfwl; else this.plfwl = "-";
        if(outslp!="" && outslp != null) this.outslp = outslp; else this.outslp = "-";
        if(len!="" && len != null) this.len = len; else this.len = "-";
        if(inslp!="" && inslp != null) this.inslp = inslp; else this.inslp = "-";
        if(edch!="" && edch != null) this.edch = edch; else this.edch = "-";
        if(edaddr!="" && edaddr != null) this.edaddr = edaddr; else this.edaddr = "-";
        if(ebmttp!="" && ebmttp != null) this.ebmttp = ebmttp; else this.ebmttp = "-";
        if(bankwith!="" && bankwith != null) this.bankwith = bankwith; else this.bankwith = "-";
        if(banknm!="" && banknm != null) this.banknm = banknm; else this.banknm = "-";
        if(banklr!="" && banklr != null) this.banklr = banklr; else this.banklr = "-";
        if(bankcd!="" && bankcd != null) this.bankcd = bankcd; else this.bankcd = "-";
        if(estnm!="" && estnm != null) this.estnm = estnm; else this.estnm = "-";
        if(bsncd!="" && bsncd != null) this.bsncd = bsncd; else this.bsncd = "-";
        if(addr!="" && addr != null) this.addr = addr; else this.addr = "-";
        if(lon!="" && lon != null) this.lon = lon; else this.lon = "-";
        if(lat!="" && lat != null) this.lat = lat; else this.lat = "-";
        if(rivnm!="" && rivnm != null) this.rivnm = rivnm; else this.rivnm = "-";
        if(tmx!="" && tmx != null) this.tmx = tmx; else this.tmx = "-";
        if(tmy!="" && tmy != null) this.tmy = tmy; else this.tmy = "-";
        if(admcd!="" && admcd != null) this.admcd = admcd; else this.admcd = "-";

    }
}
